# Generated by Django 3.2.5 on 2023-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230405_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='voice_register_num',
            field=models.IntegerField(default=5),
        ),
    ]
