# Generated by Django 3.2.6 on 2023-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20230410_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='filename',
            field=models.CharField(default='Video File', max_length=255),
            preserve_default=False,
        ),
    ]
