# Generated by Django 3.2.6 on 2023-04-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_media_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.CharField(default='video', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
